"""add edition fields

Revision ID: 5124dbddfa6f
Revises: 6b250c5ac58f
Create Date: 2026-01-30 11:24:28.624718

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5124dbddfa6f"
down_revision: Union[str, Sequence[str], None] = "6b250c5ac58f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("books", sa.Column("format", sa.String(length=50), nullable=True))
    op.add_column("books", sa.Column("edition", sa.String(length=100), nullable=True))
    op.add_column(
        "books",
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )
    op.add_column(
        "books",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=True,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "updated_at")
    op.drop_column("books", "created_at")
    op.drop_column("books", "edition")
    op.drop_column("books", "format")
    # ### end Alembic commands ###
