"""Add genres to books

Revision ID: 6b250c5ac58f
Revises: e654309b147c
Create Date: 2026-01-23 12:59:16.049176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b250c5ac58f'
down_revision: Union[str, Sequence[str], None] = 'e654309b147c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('genres', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'genres')
    # ### end Alembic commands ###
