"""Add status and rating to book list items, add is_default to lists

Revision ID: 7bcc3485c28c
Revises: 91c8737bf731
Create Date: 2026-01-15 16:33:50.699790

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7bcc3485c28c"
down_revision: Union[str, Sequence[str], None] = "91c8737bf731"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    readingstatus = sa.Enum("TO_READ", "READING", "FINISHED", name="readingstatus")
    readingstatus.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "book_list_items",
        sa.Column(
            "status",
            readingstatus,
            nullable=False,
            server_default="TO_READ",
        ),
    )
    op.add_column("book_list_items", sa.Column("rating", sa.Integer(), nullable=True))
    op.add_column("book_lists", sa.Column("is_default", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book_lists", "is_default")
    op.drop_column("book_list_items", "rating")
    op.drop_column("book_list_items", "status")
    sa.Enum(name="readingstatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
