"""Add is_favorite to book list items

Revision ID: e654309b147c
Revises: 7bcc3485c28c
Create Date: 2026-01-16 10:23:46.500948

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e654309b147c"
down_revision: Union[str, Sequence[str], None] = "7bcc3485c28c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "book_list_items",
        sa.Column("is_favorite", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book_list_items", "is_favorite")
    # ### end Alembic commands ###
